/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchSymbolRouteImport } from './routes/research.$symbol'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSymbolRoute = ResearchSymbolRouteImport.update({
  id: '/research/$symbol',
  path: '/research/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/research/$symbol': typeof ResearchSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/research/$symbol': typeof ResearchSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/research/$symbol': typeof ResearchSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portfolio' | '/watchlist' | '/research/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portfolio' | '/watchlist' | '/research/$symbol'
  id: '__root__' | '/' | '/portfolio' | '/watchlist' | '/research/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  WatchlistRoute: typeof WatchlistRoute
  ResearchSymbolRoute: typeof ResearchSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$symbol': {
      id: '/research/$symbol'
      path: '/research/$symbol'
      fullPath: '/research/$symbol'
      preLoaderRoute: typeof ResearchSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  WatchlistRoute: WatchlistRoute,
  ResearchSymbolRoute: ResearchSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
